version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - datavolume:/var/lib/mysql

  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/cotk_dashboard/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  datavolume:

