# Generated by Django 2.2.3 on 2019-07-02 16:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('check', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_user', models.CharField(max_length=50)),
                ('git_repo', models.CharField(max_length=50)),
                ('git_commit', models.CharField(max_length=40)),
                ('result', django_mysql.models.JSONField(default=dict)),
                ('other_config', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
