# Generated by Django 2.2.3 on 2019-08-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.CharField(blank=True, max_length=100)),
                ('args', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('working_dir', models.CharField(blank=True, max_length=50)),
                ('git_user', models.CharField(max_length=50)),
                ('git_repo', models.CharField(max_length=50)),
                ('git_commit', models.CharField(max_length=40)),
                ('record_information', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('result', django_mysql.models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('clsname', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Record')),
            ],
        ),
    ]
