# Generated by Django 2.2.3 on 2019-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
