# Generated by Django 2.2.3 on 2019-07-27 07:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_record_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='args',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='entry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_information',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
