# Generated by Django 2.2.3 on 2019-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190727_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
