# Generated by Django 2.2.3 on 2019-08-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_record_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='file_id',
        ),
        migrations.CreateModel(
            name='Dataloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('clsname', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Record')),
            ],
        ),
    ]
